// ===================================
// == 常用按鈕區數據 ==
// ===================================
// 頂部橫向滾動區域的按鈕（共 64 個）

const commonButtonData = [
    { name: "chatgpt", imageUrl: "https://i.ibb.co/6Jv2qS2p/chatgpt.jpg", linkUrl: "https://chat.openai.com/chat" },
    { name: "claude", imageUrl: "https://i.ibb.co/P2hQFNQ/claude.jpg", linkUrl: "https://claude.ai/chat/" },
    { name: "gemini", imageUrl: "https://i.ibb.co/vQp5dmG/Gemini.jpg", linkUrl: "https://ai.google.dev/" },
    { name: "deep research", imageUrl: "https://i.ibb.co/W4SdYkSm/Deep-Research.jpg", linkUrl: "https://gemini.google.com/app" },
    { name: "google opal", imageUrl: "https://i.ibb.co/Ngd14DXf/Opal.jpg", linkUrl: "https://opal.google/?mode=canvas" },
    { name: "enterprise", imageUrl: "https://i.ibb.co/4gSSg97P/Gemini-Enterprise.jpg", linkUrl: "https://cloud.google.com/gemini-enterprise?hl=zh_cn" },
    { name: "notebook lm", imageUrl: "https://i.ibb.co/JjDjPvqZ/notebook-LM.jpg", linkUrl: "https://notebooklm.google.com/" },
    { name: "antigravity", imageUrl: "https://i.ibb.co/7xm4TBQj/antigravity-1.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/antigravity" },
    { name: "xgrok", imageUrl: "https://i.ibb.co/SD7DPfnh/xgrok.jpg", linkUrl: "https://x.com/i/grok" },
    { name: "grok imagine", imageUrl: "https://i.ibb.co/Kp2NLt0N/grok-imagine.jpg", linkUrl: "https://grok.com/imagine" },
    { name: "deepseek", imageUrl: "https://thumbs2.imgbox.com/87/77/1nutdiE8_t.jpg", linkUrl: "https://chat.deepseek.com/" },
    { name: "perplexity", imageUrl: "https://i.ibb.co/Kch7rNLn/perplexity.jpg", linkUrl: "https://www.perplexity.ai/" },
    { name: "nvidia", imageUrl: "https://i.ibb.co/5XNsrWKs/nvidia-1.jpg", linkUrl: "https://build.nvidia.com/explore/discover" },
    { name: "manus", imageUrl: "https://i.ibb.co/GvfJVcw6/Manus.jpg", linkUrl: "https://manus.im/" },
    { name: "skywork ai", imageUrl: "https://i.ibb.co/d0Xmmgp4/skywork.jpg", linkUrl: "https://skywork.ai/" },
    { name: "mgx", imageUrl: "https://i.ibb.co/ynPbg78Q/mgx.jpg", linkUrl: "https://mgx.dev/" },
    { name: "ponder", imageUrl: "https://i.ibb.co/JWQPxwd7/ponder-1.jpg", linkUrl: "https://ponder.ing/zh_hant/" },
    { name: "glm", imageUrl: "https://i.ibb.co/gMHXZ5kL/Z-ai.jpg", linkUrl: "https://chat.z.ai/" },
    { name: "qwen image", imageUrl: "https://i.ibb.co/HL2030nH/resized-image-2.jpg", linkUrl: "https://chat.qwen.ai/" },
    { name: "wan", imageUrl: "https://thumbs2.imgbox.com/cb/b0/ZTdUPbFM_t.jpg", linkUrl: "https://create.wan.video/explore" },
    { name: "doubao", imageUrl: "https://i.ibb.co/B2GZ0dMx/doubao.jpg", linkUrl: "https://www.doubao.com/chat/" },
    { name: "qingyan", imageUrl: "https://i.ibb.co/zTk2S93v/qingyan.jpg", linkUrl: "https://chatglm.cn/" },
    { name: "roboneo", imageUrl: "https://i.ibb.co/RT3MQ90f/resized-image-1.jpg", linkUrl: "https://www.roboneo.com/home" },
    { name: "lmarena", imageUrl: "https://i.ibb.co/Mkddh98R/lmarena.jpg", linkUrl: "https://lmarena.ai/" },
    { name: "lovart", imageUrl: "https://i.ibb.co/TBYbtSg6/lovart.jpg", linkUrl: "https://www.lovart.ai/home" },
    { name: "flux 2.0", imageUrl: "https://i.ibb.co/kV3tsP5J/flux2.jpg", linkUrl: "https://bfl.ai/" },
    { name: "genspark ai", imageUrl: "https://i.ibb.co/W4X5pNHn/genspark.jpg", linkUrl: "https://www.genspark.ai/" },
    { name: "yupp ai", imageUrl: "https://i.ibb.co/Jw84rPwx/yupp-ai.jpg", linkUrl: "https://yupp.ai/" },
    { name: "kiira", imageUrl: "https://i.ibb.co/fd4J9tQV/kiira-1.jpg", linkUrl: "https://www.kiira.ai/chat" },
    { name: "dphn", imageUrl: "https://i.ibb.co/N26HnYtp/dphn-1.jpg", linkUrl: "https://chat.dphn.ai/" },
    { name: "reve", imageUrl: "https://i.ibb.co/ZRtyHq76/reve-logo.jpg", linkUrl: "https://preview.reve.art/" },
    { name: "youmind", imageUrl: "https://i.ibb.co/ycrh7hbL/youmind.jpg", linkUrl: "https://youmind.com/" },
    { name: "whisk", imageUrl: "https://i.ibb.co/HDZLH5Qf/whisk.jpg", linkUrl: "https://labs.google/fx/zh/tools/whisk" },
    { name: "neocities", imageUrl: "https://i.ibb.co/StQpZjJ/neocities.jpg", linkUrl: "https://neocities.org/" },
    { name: "button ui", imageUrl: "https://i.ibb.co/mcNtQTJ/button-ui.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/buttonui" },
    { name: "rectangle snip", imageUrl: "https://i.ibb.co/fGrmvWGM/rectangle-snip-tool.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/rectangle_snip_tool" },
    { name: "imgbb", imageUrl: "https://i.ibb.co/bz5ydnn/imgbb.jpg", linkUrl: "https://zh-tw.imgbb.com/" },
    { name: "liveweave", imageUrl: "https://i.ibb.co/RgNV27C/liveweave.jpg", linkUrl: "https://liveweave.com/" },
    { name: "adguard", imageUrl: "https://i.ibb.co/6PtL6pg/AdGuard.jpg", linkUrl: "https://adguard.com/zh_tw/adguard-temp-mail/overview.html" },
    { name: "hotmail", imageUrl: "https://i.ibb.co/jb7XNPw/hotmail.jpg", linkUrl: "https://www.microsoft.com/zh-tw/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook?deeplink=%2fowa%2f%3frealm%3dhotmail.com&sdf=0" },
    { name: "infinicloud", imageUrl: "https://i.ibb.co/pffJtNH/infini-cloud.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/infinicloud" },
    { name: "fdm", imageUrl: "https://i.ibb.co/nMHSkZQS/Free-Download-Manager.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/downvedio_box" },
    { name: "codeformer", imageUrl: "https://i.ibb.co/jZT4NCz/codeformer.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/codeformer" },
    { name: "canva", imageUrl: "https://i.ibb.co/mqzXKNQ/canva.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/canva" },
    { name: "photopea", imageUrl: "https://i.ibb.co/GM7LcpL/photopea.jpg", linkUrl: "https://www.photopea.com/" },
    { name: "vectorpea", imageUrl: "https://i.ibb.co/xGVbTPX/vectorpea.jpg", linkUrl: "https://www.vectorpea.com/" },
    { name: "figma", imageUrl: "https://i.ibb.co/cCsd8WL/Figma.jpg", linkUrl: "https://www.figma.com/" },
    { name: "squoosh", imageUrl: "https://i.ibb.co/KXb7MVK/squoosh.jpg", linkUrl: "https://squoosh.app/" },
    { name: "movie compression", imageUrl: "https://i.ibb.co/CMC2gDG/Movie-Compression.jpg", linkUrl: "https://tools.rotato.app/compress" },
    { name: "mp4 to mp3", imageUrl: "https://i.ibb.co/f8BTN2c/mp4-to-mp3.jpg", linkUrl: "https://cloudconvert.com/mp4-to-mp3" },
    { name: "diffchecker", imageUrl: "https://i.ibb.co/N7FygyG/diffchecker.jpg", linkUrl: "https://www.diffchecker.com/zh-Hant/image-compare/" },
    { name: "vectorizer", imageUrl: "https://i.ibb.co/0V2KXyVv/vectorizer.jpg", linkUrl: "https://vectorizer.com/zh/" },
    { name: "beart", imageUrl: "https://i.ibb.co/4g3YrhgR/beart.jpg", linkUrl: "https://beart.ai/zh/face-swap/" },
    { name: "aienhancer", imageUrl: "https://i.ibb.co/5WbWNPGF/aienhancer-1.jpg", linkUrl: "https://aienhancer.ai/" },
    { name: "magiceraser", imageUrl: "https://i.ibb.co/pr0tbj5D/magicstudio.jpg", linkUrl: "https://magicstudio.com/magiceraser/" },
    { name: "watermark", imageUrl: "https://i.ibb.co/7z7BpFS/watermark.jpg", linkUrl: "https://huggingface.co/spaces/Sanster/Lama-Cleaner-lama" },
    { name: "ai text remover", imageUrl: "https://i.ibb.co/fV4p56x0/AI-Text-Remover.jpg", linkUrl: "https://huggingface.co/spaces/aiqcamp/REMOVAL-TEXT-IMAGE" },
    { name: "insmind", imageUrl: "https://i.ibb.co/PdXZWmB/insmind.jpg", linkUrl: "https://www.insmind.com/" },
    { name: "line", imageUrl: "https://i.ibb.co/r0nDKqx/line.jpg", linkUrl: "https://lonlontwo2022.neocities.org/control/line" },
    { name: "quickmark", imageUrl: "https://i.ibb.co/K0gCyPK/QR.jpg", linkUrl: "https://www.qrcode-monkey.com/" },
    { name: "deepsider", imageUrl: "https://i.ibb.co/JWtJVLjP/Deep-Sider.jpg", linkUrl: "https://chromewebstore.google.com/detail/deepsiderai-sidebar-deeps/dfbnddndcmilnhdfmmaolepiaefacnpo?utm_source=item-share-cb" },
    { name: "astar vpn", imageUrl: "https://i.ibb.co/XqJyYnt/Astar-VPN.jpg", linkUrl: "https://chromewebstore.google.com/detail/astar-vpn-free-and-fast-v/jajilbjjinjmgcibalaakngmkilboobh" },
    { name: "md5", imageUrl: "https://i.ibb.co/n60gqXx/MD5.jpg", linkUrl: "https://coding.tools/tw/md5" },
    { name: "comfy ui", imageUrl: "https://i.ibb.co/7wKdZsj/comfy.jpg", linkUrl: "https://www.comfy.org/download" }
];
